//COMMON CPU FUNCTIONS
#define FUNCTION_ACK 0x01
#define FUNCTION_UC_RESET 0x02
#define FUNCTION_MODULE_INFO 0x03
#define FUNCTION_FUNCTION_NOT_FOUND 0x04
#define FUNCTION_BAD_PARAM 0x05
#define FUNCTION_OK 0x06

//COMMON
#define FUNCTION_GET_STATUS 0x10
#define FUNCTION_GET_CONFIG 0x13
#define FUNCTION_SET_CONFIG 0x14

//RELAY
#define FUNCTION_GET_RELAY 0x30
#define FUNCTION_SET_RELAY 0x31

//INPUT
#define FUNCTION_GET_INPUT 0x40
#define FUNCTION_GET_TEMPERATURE 0x41
#define FUNCTION_GET_HUMIDITY 0x41
#define FUNCTION_GET_TEMPERATURE_HUMIDITY 0x41

//BLIND
#define FUNCTION_GET_BLIND 0x41
#define FUNCTION_SET_BLIND 0x42