//COMMON CPU FUNCTIONS
#define FUNCTION_ACK 0x01
#define FUNCTION_UC_RESET 0x02

//COMMON
#define FUNCTION_GET_STATUS 0x10
#define FUNCTION_GET_ENTITY 0x11
#define FUNCTION_SET_ENTITY 0x12
#define FUNCTION_GET_CONFIG 0x13
#define FUNCTION_SET_CONFIG 0x14
